### ISSUE TITLE
help me plz..

### ISSUE THREAD

**Issue by taegyeong-lee** [lorepirri/jekyll-theme-simple-blog#1]
I forked this rp.. and, renamed "myname.github.io" 
but this error was occurred " Your site is having problems building: Page build failed. For more information, see https://help.github.com/articles/troubleshooting-github-pages-builds/."

..plz...

**Comment by lorepirri** [comment]
Hi,
thanks for reporting,

Yeah somehow github pages configuration got lost when I switched to Gitlab.

I can't looking into this right in these days, but as soon as I can I will, in the meanwhile you could try it on gitlab, just forking it there,

Best

**Comment by taegyeong-lee** [comment]
I found error reason..
because of Facebook api  and comment << so I resolved this error and I applied your best theme at my GitHub IO page 
thank you very much ~!!

**Comment by lorepirri** [comment]
Oh very nice, could you please key me know where is the error? What made it works? So I can fix it. Thanks for helping out to make it better!

**Comment by taegyeong-lee** [comment]
um..
I want to apply Facebook comment, but if I apply Facebook publish_id at config_yml, GitHub page occur this error( "Liquid Exception: no implicit conversion of Array into String in /_layouts/post.html
Fatal: TypeError
       no implicit conversion of Array into String")

but 127.0.0.1 does not occurred this error ; so I do not know why this error was occurred 
do you know this error ?..


my GitHub io : https://etilelab.github.io

**Comment by lorepirri** [comment]
In your _config.yml:
`publisher_id: [160960154506650]`
Should be:
`publisher_id: 160960154506650`

This only won't enable the comments, there's cleaning of the code needed here eheh my mistake.

To enable the comments, the FB SDK must be loaded at the beginning and currently (wrongly) this is done so only specifying the app_id (have a look at _layouts/default.html)

The app_id is the id of the Facebook application (you must create one), but for the comments only it is not needed, so you can remove it from the SDK loading querystring in _layout/default.html , and you can remove the conditional as well.

The line:

      js.src = "//connect.facebook.net/{{ page-lang-country }}/sdk.js#xfbml=1&version=v2.10&appId={{ site.facebook.app_id }}";

Becomes:

      js.src = "//connect.facebook.net/{{ page-lang-country }}/sdk.js#xfbml=1&version=v2.10";

For more info about fb comments plugin: https://developers.facebook.com/docs/plugins/comments

Let me know if it works!

**Comment by taegyeong-lee** [comment]
Thank you for your help
I visited Facebook developer comments plugin and I got my app code. 
and I changed my code, published_id : [19~~] -> published_id : myappcode ,
but this error was occurred !!! ㅠㅠ.. however  I resolved this error.

1. I changed your app code to my app code 
2. I changed js src and div tag (Facebook comments)
3. I excepted published_id and enabled app_id
4. facebook comments.html (include) -> {% if site.facebook.published_id %} ->  {% if site.facebook.app_id %}


thank you~~~

**Comment by lorepirri** [comment]
I see it is now working :) I am glad you made it!

If you also want the Like/Share button to appear, modify also the conditional in the file `_includes/facebook-like-post.html` in the same way: {% if site.facebook.published_id %} -> {% if site.facebook.app_id %}

**Comment by taegyeong-lee** [comment]
thank you very much !!!!!
you are very very kind..
